### ISSUE TITLE
Processed datasets?

### ISSUE THREAD

**Issue by bladeols** [A4Bio/OpenCPD#1]
Hi,

I am trying to download the processed datasets used by this repo, but the links don't seem to point to an appropriate download location (e.g. [here](https://arxiv.org/abs/2010.11929)). Is this repo complete and usable as written in the README.md?

**Comment by forrest-yijie-zhang** [comment]
Hi, sorry for not updating the latest README.md, otherwise you can find the processed dataset here: https://drive.google.com/drive/folders/1O8pUC25XVdtuweAmvIaanOk8cSuW_a_q?usp=sharing 

Thanks!
