### ISSUE TITLE
Unable to fetch training codes

### ISSUE THREAD

**Issue by Lim-ZQ** [A4Bio/OpenCPD#4]
The release branch doesn't contain run folder and main.py. Can you provide these training code? Thank you!

**Comment by ABOWLofFish** [comment]
having the same issue \lol

**Comment by forrest-yijie-zhang** [comment]
Hello,

Thanks to all of you for the careful review of our project. However, the paper proposed the dataset is under review now, we plan to open-source the completed version after it is accepted. 

Best,
Authors

**Comment by onenoc** [comment]
Hi, the paper got in late last year but it still doesn't have these: can you add them?
