### ISSUE TITLE
Broken links to datasets

### ISSUE THREAD

**Issue by KoubaPetr** [A4Bio/OpenCPD#5]
Hello,

I would like to point out that the link to the datasets, both from the releases as well as from README (https://www.idrive.com/idrive/sh/sh?k=p9b2y3l6i5), pointing to iDrive leads to the following error message "The shared link you are trying to access has either been deleted or expired".

In a different issue, you shared a Google Drive link. Are the contents the same? Or were the data in the release more processed?

Best,
Petr

**Comment by shydyl** [comment]
+1

**Comment by GuangtaoLyu** [comment]
+1

**Comment by forrest-yijie-zhang** [comment]
Hi,
Sorry for the late reply, we have provided a permanent link for both the datasets in replace to the previous link, please find here: https://zenodo.org/records/10778307 

Thanks
